language: python
services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - docker build -t "$TRAVIS_REPO_SLUG:latest" -t "$TRAVIS_REPO_SLUG:$(git log -1 --pretty=%h)" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$TRAVIS_REPO_SLUG:$(git log -1 --pretty=%h)"
  - docker push "$TRAVIS_REPO_SLUG:latest"
  - docker logout
